## Built with "podman build --no-cache -t nginx:latest -f Containerfile_mainApplication ."
## can also "podman push localhost/nginx:latest registry.com/username/imageName:YourRemoteNewTag

## Using nginx for reference of a "known technology" application per dynatrace
FROM docker.io/library/nginx:1.25.3

## This is due to some OpenShift clusters being restrictive with the permissions/ownership (DEMO ONLY - dont do this in prod)
USER root
RUN chown -R nginx:0 /var/cache/nginx /var/run/ && \
    chmod -R 775 /var/log/nginx /var/cache/nginx /var/run/ && \
    sed -i 's/80/8080/g' /etc/nginx/conf.d/default.conf

## Sample start of nginx app
## This image creates a /var/log/nginx/access.log and /var/log/nginx/error.log
## View deployment.yaml to see how I split the two for sidecar example purpose
CMD ["nginx", "-g", "daemon off;"]